### ISSUE TITLE
[FEATURE REQUEST] 建议加入自定义单词列表导入和导出功能

### ISSUE THREAD

**Issue by erbanku** [luyuhuang/DWords2#10]
在日常生活和工作中会遇到一些新词汇，一般都是很分散的那种，我一般会把这些新词汇存在一个 `.TXT` 文件里，每行一个，个人认为尽快的掌握这些词汇对学习英语帮助更大（毕竟这些词汇是从某些有语境的文章记下来的）。所以希望 DWords 增加 `自定义单词列表导入功能` 和 `带释义导出为PDF功能（用来打印下来背）` ，我觉得增加这两个功能该软件绝对会更 awesome 和实用，谢谢。

## `.TXT`文件大概长这样：
```
verdict
grugbrain
Chop
punch
aggregation
Regression
Amplify
lured
regime
indictment
infiltrating
rigorous
vetting
unwittingly
espionage
espionage
recruiter
revelations
recruitment
indictment
payroll
penetrate
```

**Comment by luyuhuang** [comment]
有这个功能呀, 进入 plans, 点击 new plan, 然后选 import. 就这种按行分隔的单词列表就行, 只要把后缀改成 `.csv`.

**Comment by erbanku** [comment]
> 有这个功能呀, 进入 plans, 点击 new plan, 然后选 import. 就这种按行分隔的单词列表就行, 只要把后缀改成 `.csv`.

感谢，找到导入功能了（再增加个 TXT 导入感觉会更好，不过也够用）。希望再有个 `带释义导出功能` ，导出为 A4 纸大小的 PDF 文件，用来打印下来背诵记忆，谢谢。

**Comment by luyuhuang** [comment]
这个可以有

**Comment by GrimPixel** [comment]
尚沒有對 TSV 的支持，有點美中不足。
