### ISSUE TITLE
建议改成弹幕不可点击

### ISSUE THREAD

**Issue by TRQYC** [luyuhuang/DWords2#4]
1. 目前弹幕可以点击导致影响工作，不小心就点到了。
2. 如何添加其他词典目前不知道如何操作, 粘了与一个金山词霸的url地址不对。

**Comment by luyuhuang** [comment]
弹幕是否可点击可以加一个开关设置. 至于外部词典, DWords 会将单词追加到词典的 URL 后面并访问. 所以金山词霸的 URL 应该是 https://www.iciba.com/word?w=

**Comment by TRQYC** [comment]
> 弹幕是否可点击可以加一个开关设置. 至于外部词典, DWords 会将单词追加到词典的 URL 后面并访问. 所以金山词霸的 URL 应该是 https://www.iciba.com/word?w=

看了下代码合上去了，可以发个release吗

**Comment by luyuhuang** [comment]
嗯, 我还想再加点别的东西, 可能还需要几天

**Comment by luyuhuang** [comment]
v0.1.0 release 了
