### ISSUE TITLE
坚果云同步失败

### ISSUE THREAD

**Issue by irrealizable** [luyuhuang/DWords2#8]
我的坚果云是用QQ邮箱注册的，当我在user name复制我的邮箱账号之后，@qq.com会消失，无法和坚果云建立联系
![image](https://user-images.githubusercontent.com/56907077/168320123-f7dfa538-64da-4220-ac76-377a040caa45.png)

**Comment by luyuhuang** [comment]
会消失? 你是说 "User name" 这一栏无法输入邮箱吗?

**Comment by irrealizable** [comment]
> 会消失？你是说“用户名”这个栏不能输入邮箱吗？

是的

**Comment by luyuhuang** [comment]
这么神奇吗, 我这边没这个问题呀, 复制和手打都可以. 能录个屏吗

![username](https://user-images.githubusercontent.com/10300685/168413991-3284022d-561b-4322-9ba0-27cbcb79c6b4.gif)

**Comment by irrealizable** [comment]
![20220514_143737](https://user-images.githubusercontent.com/56907077/168414492-a2dedcce-f087-42ae-97fc-600c02295fd0.gif)

**Comment by luyuhuang** [comment]
我复现这个问题了, 我查下

**Comment by luyuhuang** [comment]
v0.2.3 修复了这个问题
