### ISSUE TITLE
如何导入单词

### ISSUE THREAD

**Issue by macOSWk** [luyuhuang/DWords2#9]
学生党觉得软件很赞 👍  另外 导入背单词 使用的数据是怎样的 我用欧路词典的csv导入错误
<img width="1012" alt="截屏2022-05-21 11 43 00" src="https://user-images.githubusercontent.com/86730293/169634146-24880903-73b6-4543-9f03-7f6187c414c6.png">

**Comment by luyuhuang** [comment]
最简单的方式是一个按行分隔的单词列表, 每行就是一个单词. 这会使用内置字典里的释义. 记得先在设置里将词典改成 English-Chinese

```csv
apple
banana
cat
dog
egg
```

或者用两列, 一列是单词, 一列是释义

```csv
apple,苹果
banana,香蕉
cat,猫
dog,狗
egg,鸡蛋
```

**Comment by macoswk** [comment]
明白了 两列表格搞定了
<img width="1012" alt="截屏2022-05-21 12 22 27" src="https://user-images.githubusercontent.com/86730293/169635189-53488a2f-b53b-4834-89f3-41fcf02a36ee.png">
